# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='price',
            name='description_part',
            field=models.CharField(max_length=200, verbose_name='Описание запчасти'),
        ),
        migrations.AlterField(
            model_name='price',
            name='import_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='price',
            name='import_filename',
            field=models.CharField(max_length=200, verbose_name='Файл загрузки'),
        ),
        migrations.AlterField(
            model_name='price',
            name='our_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Розничная цена НАША!!!'),
        ),
        migrations.AlterField(
            model_name='price',
            name='partnumber',
            field=models.CharField(max_length=50, verbose_name='Номер запчасти'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_speed_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Закупочная цена СР'),
        ),
        migrations.AlterField(
            model_name='price',
            name='quantity_stock_msk',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Склад МСК'),
        ),
        migrations.AlterField(
            model_name='price',
            name='quantity_stock_spb',
            field=models.DecimalField(decimal_places=5, max_digits=12, verbose_name='Склад СПБ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rrc_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Розницная цена дилера'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Закупочная цена акция'),
        ),
    ]
