# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0002_auto_20151216_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description_part',
            field=models.TextField(max_length=200, verbose_name='Описание запчасти'),
        ),
        migrations.AlterField(
            model_name='price',
            name='import_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
