# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0003_auto_20151216_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='partnumber',
            field=models.TextField(max_length=50, verbose_name='Номер запчасти'),
        ),
    ]
