# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0006_auto_20151216_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='import_filename',
        ),
        migrations.AddField(
            model_name='price',
            name='filename_imp',
            field=models.CharField(default=datetime.datetime(2015, 12, 19, 19, 27, 49, 784179, tzinfo=utc), max_length=250, verbose_name='Файл загрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='description_part',
            field=models.TextField(verbose_name='Описание запчасти'),
        ),
    ]
