# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import impprice.models


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0007_auto_20151219_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_filenames', models.FileField(upload_to=impprice.models.get_upload_file_name, verbose_name='Файл загрузки')),
            ],
        ),
    ]
