# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0008_fileprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileprice',
            options={'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterField(
            model_name='price',
            name='filename_imp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impprice.FilePrice'),
        ),
    ]
