# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import impprice.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160217_1821'),
        ('impprice', '0009_auto_20151220_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='filename_imp',
        ),
        migrations.AlterModelOptions(
            name='fileprice',
            options={'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AddField(
            model_name='fileprice',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='fileprice',
            name='import_filenames',
            field=models.FileField(upload_to=impprice.models.get_upload_file_name, verbose_name='Файл прайса'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]