# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import impprice.models


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0010_auto_20160224_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprice',
            name='import_filenames',
            field=models.FileField(upload_to=impprice.models.get_upload_file_name, verbose_name=b'\xd0\xa4\xd0\xb0\xd0\xb9\xd0\xbb \xd0\xbf\xd1\x80\xd0\xb0\xd0\xb9\xd1\x81\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='fileprice',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]