# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0011_auto_20160901_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprice',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]