# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impprice', '0016_fileprice_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileprice',
            options={'ordering': ('-created_at',), 'verbose_name': '\u041f\u0440\u0430\u0439\u0441', 'verbose_name_plural': '\u041f\u0440\u0430\u0439\u0441\u044b'},
        ),
    ]
