# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import supplier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_auto_20160925_1625'),
        ('offer', '0012_offer_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_invoice', models.CharField(default=supplier.models.get_number_invoice, max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('status', models.PositiveIntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('stock_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': '\u041d\u0430\u043a\u043b\u0430\u0434\u043d\u0430\u044f',
                'verbose_name_plural': '\u041d\u0430\u043a\u043b\u0430\u0434\u043d\u044b\u0435',
            },
        ),
        migrations.CreateModel(
            name='ItemInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e')),
                ('quantity_in', models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u043e \u0444\u0430\u043a\u0442\u0443')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='\u0417\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductManufacturer', verbose_name='\u0411\u0440\u0435\u043d\u0434')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_invoice', to='supplier.Invoice', verbose_name='\u041d\u0430\u043a\u043b\u0430\u0434\u043d\u0430\u044f')),
                ('offers', models.ManyToManyField(to='offer.Offer', verbose_name='\u0417\u0430\u044f\u0432\u043a\u0438')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434')),
            ],
            options={
                'ordering': ('invoice',),
                'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f \u043d\u0430\u043a\u043b\u0430\u0434\u043d\u043e\u0439',
                'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438 \u043d\u0430\u043a\u043b\u0430\u0434\u043d\u043e\u0439',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('name', models.TextField(blank=True, max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('inn', models.IntegerField(default=0, verbose_name='\u0418\u041d\u041d')),
                ('ogrn', models.IntegerField(default=0, verbose_name='\u041e\u0413\u0420\u041d')),
                ('kpp', models.IntegerField(default=0, verbose_name='\u041a\u041f\u041f')),
                ('contact', models.TextField(blank=True, max_length=256, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, default='', max_length=75, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, max_length=256, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('balance', models.IntegerField(default=0, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441')),
                ('stock', models.ManyToManyField(to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434\u044b')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier', verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a'),
        ),
    ]
