# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20170512_2000'),
        ('supplier', '0002_auto_20161026_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminvoice',
            name='orders',
            field=models.ManyToManyField(null=True, to='orders.Order', verbose_name='\u0417\u0430\u044f\u0432\u043a\u0438'),
        ),
    ]
