# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_stock_color_stock'),
        ('lk', '0003_auto_20160208_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number_order', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт')),
                ('address', models.CharField(max_length=256, null=True, verbose_name='Адрес')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Контактное лицо')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.Accounts', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.Order', verbose_name='Номер заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Price', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['-count'],
                'verbose_name': 'Позиция заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Статусы',
                'verbose_name': 'Статус',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderStatus', verbose_name='Статус'),
        ),
    ]
