# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160216_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Закупка'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
