# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160217_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Закупка'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
        ),
    ]
