# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160403_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Закупка'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Цена'),
        ),
    ]
