# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20160403_1640'),
        ('orders', '0007_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='id_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='Склад'),
        ),
    ]
