# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderposition_id_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.Accounts', verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name=b'\xd0\x90\xd0\xb4\xd1\x80\xd0\xb5\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xba\xd1\x80\xd1\x8b\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0\xd1\x80\xd0\xb8\xd0\xb9'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xd0\xa1\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbd\xd1\x82\xd0\xb0\xd0\xba\xd1\x82\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbb\xd0\xb8\xd1\x86\xd0\xbe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderStatus', verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb\xd0\xb8\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='id_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.Order', verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xba\xd1\x83\xd0\xbf\xd0\xba\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name=b'\xd0\xa6\xd0\xb5\xd0\xbd\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name=b'\xd0\xa2\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x80'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=128, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
