# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderposition_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(default=b'#000', help_text='HEX \u0446\u0430\u0435\u0442, as #RRGGBB', max_length=7, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
    ]
