# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20161026_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.Accounts', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0442'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u043e\u0435 \u043b\u0438\u0446\u043e'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_order',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderStatus', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='id_stock',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='orders.Order', verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='\u0417\u0430\u043a\u0443\u043f\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='price_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
