# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20161026_1514'),
        ('orders', '0014_auto_20170423_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Invoice', verbose_name='\u041d\u0430\u043a\u043b\u0430\u0434\u043d\u0430\u044f'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='status_order',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438'),
        ),
    ]
