# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.FloatField(verbose_name='Закупочная цена')),
                ('purchase_speed_price', models.FloatField(verbose_name='Закупочная цена СР')),
                ('sale_price', models.FloatField(verbose_name='Закупочная цена акция')),
                ('rrc_price', models.FloatField(verbose_name='Розницная цена дилера')),
                ('our_price', models.FloatField(verbose_name='Розничная цена НАША!!!')),
            ],
            options={
                'verbose_name_plural': 'Цены',
                'verbose_name': 'Цена',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.BigIntegerField(unique=True, verbose_name='Номер запчасти')),
                ('description', models.TextField(verbose_name='Описание запчасти')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=128, verbose_name='Название')),
                ('delivery_time', models.IntegerField(verbose_name='Время доставки')),
            ],
            options={
                'verbose_name_plural': 'Склады',
                'verbose_name': 'Склад',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductCategory'),
        ),
        migrations.AddField(
            model_name='price',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Номер запчасти'),
        ),
        migrations.AddField(
            model_name='price',
            name='id_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='Склад'),
        ),
    ]
