# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='qty',
            field=models.FloatField(default=0, verbose_name='Колчество'),
            preserve_default=False,
        ),
    ]
