# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_price_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='color_stock',
            field=models.CharField(default='black', max_length=128, verbose_name='Цвет'),
        ),
    ]
