# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stock_color_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='our_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Розничная цена НАША!!!'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_speed_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Закупочная цена СР'),
        ),
        migrations.AlterField(
            model_name='price',
            name='qty',
            field=models.IntegerField(verbose_name='Колчество'),
        ),
        migrations.AlterField(
            model_name='price',
            name='rrc_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Розницная цена дилера'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Закупочная цена акция'),
        ),
    ]
