# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160217_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='purchase_speed_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='rrc_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='sale_price',
        ),
    ]
