# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160227_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='our_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Розничная цена НАША!!!'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Закупочная цена'),
        ),
    ]
