# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20160825_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossproduct',
            name='productnumber',
            field=models.CharField(max_length=128, verbose_name='Номер запчасти'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnumber',
            field=models.CharField(max_length=128, verbose_name='Номер запчасти'),
        ),
    ]
