# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160826_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossproduct',
            name='crossnumber',
            field=models.TextField(verbose_name=b'\xd0\x9a\xd1\x80\xd0\xbe\xd1\x81\xd1\x81 \xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='crossproduct',
            name='productnumber',
            field=models.CharField(max_length=128, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
        migrations.AlterField(
            model_name='price',
            name='our_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name=b'\xd0\xa0\xd0\xbe\xd0\xb7\xd0\xbd\xd0\xb8\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0 \xd0\x9d\xd0\x90\xd0\xa8\xd0\x90!!!'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xba\xd1\x83\xd0\xbf\xd0\xbe\xd1\x87\xd0\xbd\xd0\xb0\xd1\x8f \xd1\x86\xd0\xb5\xd0\xbd\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='price',
            name='qty',
            field=models.IntegerField(verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb\xd1\x87\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd1\x81\xd0\xbe\xd0\xb7\xd0\xb4\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnumber',
            field=models.CharField(max_length=128, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='productmanufacturer',
            name='name',
            field=models.CharField(default=b'BMW', max_length=128, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='color_stock',
            field=models.CharField(default=b'black', max_length=128, verbose_name=b'\xd0\xa6\xd0\xb2\xd0\xb5\xd1\x82'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delivery_time',
            field=models.IntegerField(verbose_name=b'\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f \xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_stock',
            field=models.CharField(max_length=128, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
