# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20160901_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='id_product',
        ),
        migrations.AddField(
            model_name='price',
            name='p_product',
            field=models.CharField(default=1, max_length=50, verbose_name=b'\xd0\x9d\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80 \xd0\xb7\xd0\xb0\xd0\xbf\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbb\xd0\xb0\xd0\xb4'),
        ),
    ]
