# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20160912_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'permissions': (('can_purchase_price', '\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0437\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0443\u044e \u0446\u0435\u043d\u0443'), ('can_id_stock', '\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0421\u043a\u043b\u0430\u0434')), 'verbose_name': '\u0426\u0435\u043d\u0430', 'verbose_name_plural': '\u0426\u0435\u043d\u044b'},
        ),
    ]
