# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20160918_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='brand',
            field=models.CharField(default=b'BMW', max_length=50, verbose_name='\u0411\u0440\u0435\u043d\u0434'),
        ),
        migrations.AlterField(
            model_name='crossproduct',
            name='crossnumber',
            field=models.TextField(verbose_name='\u041a\u0440\u043e\u0441\u0441 \u041d\u043e\u043c\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='crossproduct',
            name='productnumber',
            field=models.CharField(max_length=128, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
        migrations.AlterField(
            model_name='price',
            name='our_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u0420\u043e\u0437\u043d\u0438\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430 \u041d\u0410\u0428\u0410!!!'),
        ),
        migrations.AlterField(
            model_name='price',
            name='p_product',
            field=models.CharField(default=1, max_length=50, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='price',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u0417\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='price',
            name='qty',
            field=models.IntegerField(verbose_name='\u041a\u043e\u043b\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='product',
            name='partnumber',
            field=models.CharField(max_length=128, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='productmanufacturer',
            name='name',
            field=models.CharField(default=b'BMW', max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='color_stock',
            field=models.CharField(default=b'black', max_length=128, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delivery_time',
            field=models.IntegerField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_stock',
            field=models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
