# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20160925_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmanufacturer',
            name='alt_name',
            field=models.CharField(default=b'', max_length=256, verbose_name='\u0410\u043b\u044c\u0442\u0435\u0440\u043d\u0430\u0442\u0438\u0432\u043d\u044b\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
