# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170108_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to=b'img/products/', width_field=300),
        ),
    ]
