# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 15:22
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.get_upload_file_name, verbose_name='\u0424\u043e\u0442\u043e \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
