# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20170212_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='delivery_comment',
            field=models.CharField(default=b'', max_length=128, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u043f\u043e \u0441\u0440\u043e\u043a\u0430\u043c \u043f\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
