# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0014_auto_20160925_1625'),
        ('lk', '0005_auto_20160825_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='\u0417\u0430\u043a\u0443\u043f\u043e\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductManufacturer', verbose_name='\u0411\u0440\u0435\u043d\u0434')),
            ],
            options={
                'ordering': ('offer',),
                'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f',
                'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0437\u0430\u044f\u0432\u043a\u0438')),
                ('fio', models.TextField(blank=True, max_length=128, verbose_name='\u0424.\u0418.\u041e')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('creation_date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('vin', models.CharField(blank=True, default='', max_length=50, verbose_name='VIN \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.Accounts', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438',
            },
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_d', to='offer.Offer', verbose_name='\u0417\u0430\u044f\u0432\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='itemoffer',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434'),
        ),
    ]
