# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20160928_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemoffer',
            options={'ordering': ('-offer',), 'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f', 'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
    ]
