# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-created_at',), 'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438'},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0417\u0430\u043a\u0440\u044b\u0442'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d'),
            preserve_default=False,
        ),
    ]
