# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20161001_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True, max_length=256, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
