# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_auto_20160825_1633'),
        ('offer', '0008_auto_20161007_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d')),
                ('fio', models.TextField(blank=True, max_length=128, verbose_name='\u0424.\u0418.\u041e')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('email', models.EmailField(blank=True, default='', max_length=75, verbose_name='E-mail')),
                ('vin', models.CharField(blank=True, default='', max_length=50, verbose_name='VIN \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f')),
                ('address', models.TextField(blank=True, max_length=256, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('comment', models.TextField(blank=True, max_length=256, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('balance', models.IntegerField(default=0, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.Accounts', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ('-fio',),
                'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b',
            },
        ),
    ]
