# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('fio',), 'verbose_name': '\u041a\u043b\u0438\u0435\u043d\u0442', 'verbose_name_plural': '\u041a\u043b\u0438\u0435\u043d\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='itemoffer',
            options={'ordering': ('-pk',), 'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f', 'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438'},
        ),
    ]
