# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20161009_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='status_offer',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438'),
        ),
    ]
