# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_auto_20161017_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='unit_price_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True, max_length=512, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
