# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_auto_20161026_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430')),
                ('operations', models.TextField(blank=True, max_length=256, verbose_name='\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u044f')),
                ('balance_price', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='\u0421\u0443\u043c\u043c\u0430')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='offer.Customer', verbose_name='\u041a\u043b\u0438\u0435\u043d\u0442')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0431\u0430\u043b\u0430\u043d\u0441\u0430',
                'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u0431\u0430\u043b\u0430\u043d\u0441\u043e\u0432',
            },
        ),
    ]
