# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_balancehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ('-created_at',), 'verbose_name': '\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0431\u0430\u043b\u0430\u043d\u0441\u0430', 'verbose_name_plural': '\u0418\u0441\u0442\u043e\u0440\u0438\u0438 \u0431\u0430\u043b\u0430\u043d\u0441\u043e\u0432'},
        ),
        migrations.AlterField(
            model_name='balancehistory',
            name='operations',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u041e\u043f\u0435\u0440\u0430\u0446\u0438\u044f'),
        ),
    ]
