# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20161026_1514'),
        ('offer', '0018_auto_20161028_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoffer',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Invoice', verbose_name='\u041d\u0430\u043a\u043b\u0430\u0434\u043d\u0430\u044f'),
        ),
    ]
