# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_itemoffer_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aw', models.PositiveIntegerField(verbose_name='AW')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer', verbose_name='\u0417\u0430\u044f\u0432\u043a\u0430')),
            ],
            options={
                'ordering': ('-pk',),
                'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u0430',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('number', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u043f\u0447\u0430\u0441\u0442\u0438')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0431\u043e\u0442\u044b')),
            ],
            options={
                'ordering': ('-number',),
                'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u0430 \u0421\u0422\u041e',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0442\u044b \u0421\u0422\u041e',
            },
        ),
        migrations.AddField(
            model_name='workoffer',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Works', verbose_name='\u0420\u0430\u0431\u043e\u0442\u0430'),
        ),
    ]
