# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0020_auto_20170212_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoffer',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=b'0.0', max_digits=18, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
