# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0021_auto_20170215_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoffer',
            name='aw',
            field=models.PositiveIntegerField(default=0, verbose_name='AW'),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
