# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0022_auto_20170215_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='aw_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
