# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_auto_20160912_1605'),
        ('lk', '0005_auto_20160825_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('creation_date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.Accounts', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a',
                'verbose_name_plural': '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='ItemD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='\u041a\u043e\u043b-\u0432\u043e')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Draft', verbose_name='\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Stock', verbose_name='\u0421\u043a\u043b\u0430\u0434')),
            ],
            options={
                'ordering': ('draft',),
                'verbose_name': '\u041f\u043e\u0437\u0438\u0446\u0438\u044f',
                'verbose_name_plural': '\u041f\u043e\u0437\u0438\u0446\u0438\u0438',
            },
        ),
    ]
