# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemd',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_d', to='draft.Draft', verbose_name='\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'),
        ),
    ]
