# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20160919_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='name',
            field=models.TextField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
