# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_auto_20160128_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'VIN номер автомобиля', 'verbose_name_plural': 'VIN номера автомобилей'},
        ),
    ]
