# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_auto_20160208_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='cart_id',
            field=models.IntegerField(default=0, verbose_name='CART-ID'),
        ),
    ]
