# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_accounts_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='vin',
        ),
        migrations.AddField(
            model_name='accounts',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
