# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_auto_20160825_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='\u0411\u0430\u043b\u0430\u043d\u0441'),
        ),
    ]
