# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_balancehistoryaccounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancehistoryaccounts',
            name='order',
        ),
    ]
